Also requires pandas
```
✔ ~/NeMo/tools/speech_data_explorer [main|✔] 
23:02 $ python3 data_explorer.py 
Traceback (most recent call last):
  File "data_explorer.py", line 40, in <module>
    from plotly import express as px
  File "/home/kathyreid/.local/lib/python3.8/site-packages/plotly/express/__init__.py", line 10, in <module>
    raise ImportError(
ImportError: Plotly express requires pandas to be installed.
✘-1 ~/NeMo/tools/speech_data_explorer [main|✔] 
23:12 $ pip install pandas
Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-1.3.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (10.6 MB)
     |████████████████████████████████| 10.6 MB 752 kB/s 
Requirement already satisfied: numpy>=1.17.3 in /home/kathyreid/.local/lib/python3.8/site-packages (from pandas) (1.21.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/lib/python3/dist-packages (from pandas) (2.7.3)
Requirement already satisfied: pytz>=2017.3 in /usr/lib/python3/dist-packages (from pandas) (2019.3)
Installing collected packages: pandas
Successfully installed pandas-1.3.0
```