[Build] Bump bitsandbytes dependency to 0.45.5 (ubuntu 22.04 compatibility) (#13789)
* See discussion in the issue bitsandbytes-foundation/bitsandbytes/issues/1663
* In summary:
  * `v0.45.3` was using Ubuntu 24.04 which brings `gcc-13` and newer glibcxx dependency
  * `v0.45.4` is missing `libbitsandbytes_cpu.so` and hence one needs to use at least `v0.45.5` to ensure compatibility with Ubuntu 22.04 and use the CPU backend.
* This is required when using nemo/nemo-run on login nodes of cluster where gpus not available and we end-up error like:

```console
python3 -m scripts.performance.llm.pretrain_llama31 -a gcore -p main -t 00:30:00 -l /root/dgx-stage-last-tag/ -i /root/dgx-stage-last-tag//nvidia+nemo+25.02.01.sqsh ...
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
Could not load bitsandbytes native library: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /root/dgx-stage-last-tag/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so)
Traceback (most recent call last):
  File "/root/dgx-stage-last-tag/venv/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 85, in <module>
    lib = get_native_library()
  File "/root/dgx-stage-last-tag/venv/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 72, in get_native_library
    dll = ct.cdll.LoadLibrary(str(binary_path))
  File "/usr/lib/python3.10/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /root/dgx-stage-last-tag/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so)
```

Signed-off-by: Pramod Kumbhar <prkumbhar@nvidia.com>
Signed-off-by: Amir Hussein <amhussein@nvidia.com>