Fix float/integer type error in WER.update() (#4816)
Without this, `WER.update()` fails with the following exception:

    TypeError: 'float' object cannot be interpreted as an integer

This is because `scores` and `words` are initialized with 0.0,
while they are supposed to be integer variables. Fix the
initialization so that the variables have the correct type.

Signed-off-by: Fujimoto Seiji <fujimoto@clear-code.com>

Signed-off-by: Fujimoto Seiji <fujimoto@clear-code.com>